steps:
  - name: Checkout
    uses: actions/checkout@v4

  - name: Set up Node.js
    uses: actions/setup-node@v3
    with:
      node-version: '16'

  - name: Install dependencies and build
    run: |
     npm install
     npm run build

  - name: Run tests
    run: npm run test