apiVersion: apps/v1
kind: Deployment
metadata:
  name: cportal-react-app-deployment
  labels:
    app: cportal-react-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cportal-react-app
  template:
    metadata:
      labels:
        app: cportal-react-app
    spec:
      containers:
        - name: cportal-react-app
          image: 058264406380.dkr.ecr.us-east-1.amazonaws.com/cportal-react-frontend:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
