name: Build and Test

runs:
  using: "composite"
  steps:
    - name: Set up Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies and build project
      run: |
        npm install
        npm run build

    - name: Run tests
      run: npm test
