name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - include: ../build-and-test.yml

  docker:
    runs-on: ubuntu-latest
    steps:
      - include: ../docker.yml
