name: CI/CD pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Test
        uses: .github/workflows/actions/build-and-test.yml

      - name: Docker
        uses: .github/workflows/actions/docker.yml

